### ISSUE TITLE
Convert to markdown loses nested indentation of checklist

### ISSUE THREAD

**Issue by cspotcode** [stevencohn/OneMore#1583]
# Problem to Solve

Write a checklist with multiple levels of indentation.
"Copy as markdown," preserving the nested indentation.

# To Reproduce

1. Write OneNote page like this:
![image](https://github.com/user-attachments/assets/b06c754b-094a-4e77-abf9-a84825af9296)
2. Select all with Ctrl+A, Ctrl+Shift+P, "Copy as markdown"
3. Paste into Notepad

Markdown is missing indentation on the indented checklist items.

```
# Test copy as markdown issue
- [ ] Checkbox  
- [ ] Checkbox 2  
- [ ] Indented checkbox (bug: not indented in markdown)  
- [ ] Indented 2x checkbox (also bug)  
  
>Paragraph  
- [x] Indented checkbox  
- [x] Indented checkbox 2  
- [x] Indented checkbox 3  
```

# Expected Behavior

Markdown looks like this:

```
# Test copy as markdown issue
- [ ] Checkbox  
- [ ] Checkbox 2  
  - [ ] Indented checkbox (bug: not indented in markdown)  
    - [ ] Indented 2x checkbox (bug: also not indented)
  
>Paragraph  
- [x] Indented checkbox  
- [x] Indented checkbox 2  
- [x] Indented checkbox 3  
```

So it can render like this:

<details>
  <summary>Render</summary>

# Test copy as markdown issue
- [ ] Checkbox  
- [ ] Checkbox 2  
  - [ ] Indented checkbox (bug: not indented in markdown)  
    - [ ] Indented 2x checkbox (also bug)  
  
>Paragraph  
- [x] Indented checkbox  
- [x] Indented checkbox 2  
- [x] Indented checkbox 3  
</details>

# Screenshots

See above.

# Environment (if applicable)

- OneNote Version: OneNote 16.0.17928.20156
- OneMore Version 6.5.2

# Additional Context

The "Paragraph" rendering tripped me up initially, but now I understand: checkboxes are not technically list items in OneNote.  They're still paragraphs.  Yet to represent a checkbox in markdown, you must make it a list item.  So that's why the paragraph is not prefixed with a `-`.  The `>` is still confusing to me, but maybe there's a good reason for that.

Maybe that's why it's so tricky to convert indentation from OneNote into Markdown?

In this case, my intuition was very much that the checkboxes are a list, so it makes sense to preserve indentation, because it's a set of tasks and sub-tasks.  But I understand if that's too complex or too hairy to implement.

**Comment by stevencohn** [comment]
The page, as shown above, would be represented in markdown as

```markdown
# Test copy as markdown issue
[ ] Checkbox  
[ ] Checkbox 2  
    [ ] Indented checkbox (bug: not indented in markdown)  
        [ ] Indented 2x checkbox (bug: also not indented)
Paragraph  
    [x] Indented checkbox  
    [x] Indented checkbox 2  
    [x] Indented checkbox 3  
```

These are not list items so should not be prefaced with `-` hyphens. This is to attempt to match fidelity with OneNote if ever trying to convert from this generate markdown back to OneNote format. Since markdown doesn't have a good way to plainly indent text, It would look like this once converted back to OneNote:

<img width="176" alt="image" src="https://github.com/user-attachments/assets/b2270c8a-f172-496b-b9f5-28ffd33da556">

Unfortunately, that's the best that can be done without making assumption that would render other use cases invalid.

**Comment by cspotcode** [comment]
Bummer, but I get it: there's no solution for all use-cases without blowing up the complexity and adding a bunch of options.  Thanks for taking a look and for making it consistent.
